name: Ichi Token Updater (Prod)

on: workflow_dispatch

jobs:
  prod:
    name: build-deploy-prod
    runs-on: ubuntu-latest
    env:
        function-name: ichi-api-updater
        env-name: prod
        dist-directory: ./dist

    steps:

      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: npm install and build
        run: |
          npm i
          npm run build

      - name: lint
        run: |
          npm run lint

      - name: zip results
        run: |
          zip -r ../${{env.function-name}}.zip *
        working-directory: ${{env.dist-directory}}

      - name: Deploy function ${{env.function-name}}-${{env.env-name}}
        uses: appleboy/lambda-action@v0.1.3
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: ${{env.function-name}}-${{env.env-name}}
          zip_file: ./${{env.function-name}}.zip

      # If we wire up the updater to API Gateway we could potentially test the output
      # - name: Make Request
      #   id: myRequest
      #   uses: fjogeleit/http-request-action@master
      #   with:
      #     url: "http://yoursite.com/api"

      # - name: Show Response
      #   run: echo ${{ steps.myRequest.outputs.response }}
